### PR TITLE
chore: add subgraph tests to the github action 'test'

### PR DESCRIPTION
**Pull request by EmperorOrokuSaki**

### CODE REVIEW

**Comment by EmperorOrokuSaki** [comment]
We should merge the unit tests pr in this branch first and then merge this.

**Comment by jsonsivar** [comment]
The folder structure needs to be clean up here.  The gitignore changed because of the folder structure refactor so you have to delete the extra files.  I would recommend creating a new branch for this from develop to avoid any issues.

**Comment by EmperorOrokuSaki** [comment]
> The folder structure needs to be clean up here. The gitignore changed because of the folder structure refactor so you have to delete the extra files. I would recommend creating a new branch for this from develop to avoid any issues.

In order to avoid multiple merges, I suggest we wait for the subgraph unit tests PR merge first.

**Comment by EmperorOrokuSaki** [comment]
Closing the PR now. Will create a new one once #97 is merged.

**Pull request closed without merging**
